version: '3.8'

services:
  # Production API service
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: ks_ai_api_prod
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      QDRANT_HOST: ${QDRANT_HOST}
      QDRANT_PORT: ${QDRANT_PORT}
      QDRANT_API_KEY: ${QDRANT_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      DEBUG: "false"
      LOG_LEVEL: INFO
      ENVIRONMENT: production
    volumes:
      - api_uploads:/app/uploads
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: ks_ai_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    restart: unless-stopped

volumes:
  api_uploads:
    driver: local

networks:
  default:
    name: ks_ai_prod_network